### ISSUE TITLE
I am getting error json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by aftab4657** [freundTech/deepl-cli#6]
import deepl
translation, extra_data = deepl.translate("This is a test", target="DE")
print(translation)

Traceback (most recent call last):
  File "D:/PycharmProjects/deepl_translation/index.py", line 3, in <module>
    translation, extra_data = deepl.translate("This is a test", target="DE")
  File "C:\ProgramData\Anaconda3\lib\site-packages\deepl\translator.py", line 11, in translate
    sentences = _request_split_sentences(paragraphs, source, preferred_langs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\deepl\translator.py", line 71, in _request_split_sentences
    url, data=json.dumps(payload), headers=headers).json()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by freundTech** [comment]
Please see Issue #5. This broke when deepl released their official (paid) api and broke the unofficial api I used in the process. I currently don't have any plans to support the official, nor the new unofficial api.
